import { Company, FilterOptions, PaginationInfo } from '../types/company';

// Comprehensive mock company data - 100+ companies from India and Worldwide
const mockCompanies: Company[] = [
  // Indian Technology Companies
  {
    id: '1',
    name: 'Tata Consultancy Services',
    industry: 'Technology',
    location: 'Mumbai, India',
    employees: 614795,
    founded: 1968,
    revenue: '$25B+',
    description: 'Leading global IT services, consulting and business solutions organization',
    logo: '🏢',
    rating: 4.5,
    country: 'India',
  },
  {
    id: '2',
    name: 'Infosys',
    industry: 'Technology',
    location: 'Bangalore, India',
    employees: 343234,
    founded: 1981,
    revenue: '$18B+',
    description: 'Global leader in next-generation digital services and consulting',
    logo: '💼',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '3',
    name: 'Wipro',
    industry: 'Technology',
    location: 'Bangalore, India',
    employees: 250000,
    founded: 1945,
    revenue: '$10B+',
    description: 'Leading technology services and consulting company',
    logo: '🖥️',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '4',
    name: 'HCL Technologies',
    industry: 'Technology',
    location: 'Noida, India',
    employees: 219000,
    founded: 1976,
    revenue: '$12B+',
    description: 'Next-generation global technology company',
    logo: '💻',
    rating: 4.1,
    country: 'India',
  },
  {
    id: '5',
    name: 'Tech Mahindra',
    industry: 'Technology',
    location: 'Pune, India',
    employees: 157000,
    founded: 1986,
    revenue: '$6B+',
    description: 'Digital transformation, consulting and business re-engineering services',
    logo: '🚀',
    rating: 4.0,
    country: 'India',
  },
  // Indian Finance Companies
  {
    id: '6',
    name: 'HDFC Bank',
    industry: 'Finance',
    location: 'Mumbai, India',
    employees: 177000,
    founded: 1994,
    revenue: '$15B+',
    description: 'Leading private sector bank in India',
    logo: '🏦',
    rating: 4.6,
    country: 'India',
  },
  {
    id: '7',
    name: 'ICICI Bank',
    industry: 'Finance',
    location: 'Mumbai, India',
    employees: 120000,
    founded: 1994,
    revenue: '$12B+',
    description: 'Major banking and financial services company',
    logo: '💰',
    rating: 4.4,
    country: 'India',
  },
  {
    id: '8',
    name: 'State Bank of India',
    industry: 'Finance',
    location: 'Mumbai, India',
    employees: 245000,
    founded: 1806,
    revenue: '$20B+',
    description: 'Largest public sector bank in India',
    logo: '🏛️',
    rating: 4.2,
    country: 'India',
  },
  // Indian E-commerce & Retail
  {
    id: '9',
    name: 'Flipkart',
    industry: 'E-commerce',
    location: 'Bangalore, India',
    employees: 35000,
    founded: 2007,
    revenue: '$5B+',
    description: 'Leading e-commerce marketplace in India',
    logo: '🛒',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '10',
    name: 'Reliance Retail',
    industry: 'Retail',
    location: 'Mumbai, India',
    employees: 350000,
    founded: 2006,
    revenue: '$30B+',
    description: 'Largest retailer in India',
    logo: '🏬',
    rating: 4.5,
    country: 'India',
  },
  {
    id: '11',
    name: 'Zomato',
    industry: 'Food Tech',
    location: 'Gurugram, India',
    employees: 5000,
    founded: 2008,
    revenue: '$800M+',
    description: 'Food delivery and restaurant discovery platform',
    logo: '🍔',
    rating: 4.1,
    country: 'India',
  },
  {
    id: '12',
    name: 'Swiggy',
    industry: 'Food Tech',
    location: 'Bangalore, India',
    employees: 6000,
    founded: 2014,
    revenue: '$1B+',
    description: 'On-demand delivery platform',
    logo: '🍕',
    rating: 4.2,
    country: 'India',
  },
  // Indian Automotive
  {
    id: '13',
    name: 'Tata Motors',
    industry: 'Automotive',
    location: 'Mumbai, India',
    employees: 80000,
    founded: 1945,
    revenue: '$38B+',
    description: 'Leading automobile manufacturer',
    logo: '🚗',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '14',
    name: 'Mahindra & Mahindra',
    industry: 'Automotive',
    location: 'Mumbai, India',
    employees: 260000,
    founded: 1945,
    revenue: '$20B+',
    description: 'Multinational automobile manufacturer',
    logo: '🚙',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '15',
    name: 'Maruti Suzuki',
    industry: 'Automotive',
    location: 'New Delhi, India',
    employees: 35000,
    founded: 1981,
    revenue: '$12B+',
    description: 'Largest passenger vehicle manufacturer in India',
    logo: '🚘',
    rating: 4.4,
    country: 'India',
  },
  // Indian Pharma
  {
    id: '16',
    name: 'Sun Pharmaceutical',
    industry: 'Pharmaceutical',
    location: 'Mumbai, India',
    employees: 40000,
    founded: 1983,
    revenue: '$5B+',
    description: 'Leading pharmaceutical company',
    logo: '💊',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '17',
    name: 'Dr. Reddys Laboratories',
    industry: 'Pharmaceutical',
    location: 'Hyderabad, India',
    employees: 24000,
    founded: 1984,
    revenue: '$3B+',
    description: 'Integrated pharmaceutical company',
    logo: '⚕️',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '18',
    name: 'Cipla',
    industry: 'Pharmaceutical',
    location: 'Mumbai, India',
    employees: 25000,
    founded: 1935,
    revenue: '$2.5B+',
    description: 'Global pharmaceutical company',
    logo: '💉',
    rating: 4.4,
    country: 'India',
  },
  // Indian Telecom
  {
    id: '19',
    name: 'Bharti Airtel',
    industry: 'Telecommunications',
    location: 'New Delhi, India',
    employees: 23000,
    founded: 1995,
    revenue: '$15B+',
    description: 'Leading telecommunications services company',
    logo: '📱',
    rating: 4.1,
    country: 'India',
  },
  {
    id: '20',
    name: 'Reliance Jio',
    industry: 'Telecommunications',
    location: 'Mumbai, India',
    employees: 15000,
    founded: 2016,
    revenue: '$10B+',
    description: 'Largest mobile network operator in India',
    logo: '📡',
    rating: 4.3,
    country: 'India',
  },
  // US Technology Companies
  {
    id: '21',
    name: 'Apple Inc',
    industry: 'Technology',
    location: 'Cupertino, USA',
    employees: 164000,
    founded: 1976,
    revenue: '$394B+',
    description: 'Technology company specializing in consumer electronics and software',
    logo: '🍎',
    rating: 4.8,
    country: 'USA',
  },
  {
    id: '22',
    name: 'Microsoft',
    industry: 'Technology',
    location: 'Redmond, USA',
    employees: 221000,
    founded: 1975,
    revenue: '$211B+',
    description: 'Multinational technology corporation',
    logo: '⊞',
    rating: 4.7,
    country: 'USA',
  },
  {
    id: '23',
    name: 'Google',
    industry: 'Technology',
    location: 'Mountain View, USA',
    employees: 190000,
    founded: 1998,
    revenue: '$280B+',
    description: 'Multinational technology company specializing in Internet services',
    logo: '🔍',
    rating: 4.6,
    country: 'USA',
  },
  {
    id: '24',
    name: 'Amazon',
    industry: 'E-commerce',
    location: 'Seattle, USA',
    employees: 1540000,
    founded: 1994,
    revenue: '$514B+',
    description: 'Multinational technology company focusing on e-commerce and cloud computing',
    logo: '📦',
    rating: 4.5,
    country: 'USA',
  },
  {
    id: '25',
    name: 'Meta',
    industry: 'Technology',
    location: 'Menlo Park, USA',
    employees: 86000,
    founded: 2004,
    revenue: '$134B+',
    description: 'Technology company behind Facebook, Instagram, and WhatsApp',
    logo: '👥',
    rating: 4.3,
    country: 'USA',
  },
  {
    id: '26',
    name: 'Netflix',
    industry: 'Entertainment',
    location: 'Los Gatos, USA',
    employees: 12800,
    founded: 1997,
    revenue: '$33B+',
    description: 'Streaming entertainment service',
    logo: '🎬',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '27',
    name: 'Tesla',
    industry: 'Automotive',
    location: 'Austin, USA',
    employees: 127855,
    founded: 2003,
    revenue: '$96B+',
    description: 'Electric vehicle and clean energy company',
    logo: '⚡',
    rating: 4.6,
    country: 'USA',
  },
  {
    id: '28',
    name: 'NVIDIA',
    industry: 'Technology',
    location: 'Santa Clara, USA',
    employees: 29600,
    founded: 1993,
    revenue: '$60B+',
    description: 'Technology company designing graphics processing units',
    logo: '🎮',
    rating: 4.7,
    country: 'USA',
  },
  {
    id: '29',
    name: 'Intel',
    industry: 'Technology',
    location: 'Santa Clara, USA',
    employees: 131900,
    founded: 1968,
    revenue: '$63B+',
    description: 'Multinational technology corporation and semiconductor chip manufacturer',
    logo: '💾',
    rating: 4.3,
    country: 'USA',
  },
  {
    id: '30',
    name: 'IBM',
    industry: 'Technology',
    location: 'Armonk, USA',
    employees: 282100,
    founded: 1911,
    revenue: '$60B+',
    description: 'Multinational technology and consulting corporation',
    logo: '🖥️',
    rating: 4.2,
    country: 'USA',
  },
  // US Finance
  {
    id: '31',
    name: 'JPMorgan Chase',
    industry: 'Finance',
    location: 'New York, USA',
    employees: 293723,
    founded: 1799,
    revenue: '$158B+',
    description: 'Multinational investment bank and financial services company',
    logo: '🏦',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '32',
    name: 'Goldman Sachs',
    industry: 'Finance',
    location: 'New York, USA',
    employees: 49100,
    founded: 1869,
    revenue: '$59B+',
    description: 'Multinational investment bank and financial services company',
    logo: '💼',
    rating: 4.5,
    country: 'USA',
  },
  {
    id: '33',
    name: 'PayPal',
    industry: 'Fintech',
    location: 'San Jose, USA',
    employees: 30900,
    founded: 1998,
    revenue: '$29B+',
    description: 'Online payment system',
    logo: '💳',
    rating: 4.3,
    country: 'USA',
  },
  // European Companies
  {
    id: '34',
    name: 'SAP',
    industry: 'Technology',
    location: 'Walldorf, Germany',
    employees: 112000,
    founded: 1972,
    revenue: '$34B+',
    description: 'Enterprise software company',
    logo: '💻',
    rating: 4.4,
    country: 'Germany',
  },
  {
    id: '35',
    name: 'Siemens',
    industry: 'Manufacturing',
    location: 'Munich, Germany',
    employees: 311000,
    founded: 1847,
    revenue: '$78B+',
    description: 'Multinational conglomerate company',
    logo: '⚙️',
    rating: 4.5,
    country: 'Germany',
  },
  {
    id: '36',
    name: 'Volkswagen',
    industry: 'Automotive',
    location: 'Wolfsburg, Germany',
    employees: 675000,
    founded: 1937,
    revenue: '$295B+',
    description: 'Automotive manufacturer',
    logo: '🚗',
    rating: 4.3,
    country: 'Germany',
  },
  {
    id: '37',
    name: 'BMW',
    industry: 'Automotive',
    location: 'Munich, Germany',
    employees: 149000,
    founded: 1916,
    revenue: '$155B+',
    description: 'Luxury vehicle manufacturer',
    logo: '🏎️',
    rating: 4.6,
    country: 'Germany',
  },
  {
    id: '38',
    name: 'Mercedes-Benz',
    industry: 'Automotive',
    location: 'Stuttgart, Germany',
    employees: 172000,
    founded: 1926,
    revenue: '$158B+',
    description: 'Luxury automobile manufacturer',
    logo: '⭐',
    rating: 4.7,
    country: 'Germany',
  },
  {
    id: '39',
    name: 'Spotify',
    industry: 'Entertainment',
    location: 'Stockholm, Sweden',
    employees: 9800,
    founded: 2006,
    revenue: '$13B+',
    description: 'Audio streaming and media services provider',
    logo: '🎵',
    rating: 4.4,
    country: 'Sweden',
  },
  {
    id: '40',
    name: 'IKEA',
    industry: 'Retail',
    location: 'Delft, Netherlands',
    employees: 225000,
    founded: 1943,
    revenue: '$47B+',
    description: 'Multinational furniture retailer',
    logo: '🛋️',
    rating: 4.5,
    country: 'Sweden',
  },
  {
    id: '41',
    name: 'Nestle',
    industry: 'Food & Beverage',
    location: 'Vevey, Switzerland',
    employees: 275000,
    founded: 1866,
    revenue: '$103B+',
    description: 'Multinational food and drink processing conglomerate',
    logo: '🍫',
    rating: 4.3,
    country: 'Switzerland',
  },
  {
    id: '42',
    name: 'Adidas',
    industry: 'Apparel',
    location: 'Herzogenaurach, Germany',
    employees: 59000,
    founded: 1949,
    revenue: '$24B+',
    description: 'Multinational corporation that designs and manufactures shoes',
    logo: '👟',
    rating: 4.4,
    country: 'Germany',
  },
  {
    id: '43',
    name: 'LVMH',
    industry: 'Luxury Goods',
    location: 'Paris, France',
    employees: 213000,
    founded: 1987,
    revenue: '$86B+',
    description: 'Multinational luxury goods conglomerate',
    logo: '👜',
    rating: 4.6,
    country: 'France',
  },
  {
    id: '44',
    name: 'Airbus',
    industry: 'Aerospace',
    location: 'Leiden, Netherlands',
    employees: 134000,
    founded: 1970,
    revenue: '$58B+',
    description: 'European aerospace corporation',
    logo: '✈️',
    rating: 4.5,
    country: 'France',
  },
  // Asian Companies (non-India)
  {
    id: '45',
    name: 'Samsung Electronics',
    industry: 'Technology',
    location: 'Seoul, South Korea',
    employees: 267800,
    founded: 1969,
    revenue: '$234B+',
    description: 'Multinational electronics corporation',
    logo: '📱',
    rating: 4.6,
    country: 'South Korea',
  },
  {
    id: '46',
    name: 'LG Electronics',
    industry: 'Technology',
    location: 'Seoul, South Korea',
    employees: 75000,
    founded: 1958,
    revenue: '$63B+',
    description: 'Multinational electronics company',
    logo: '📺',
    rating: 4.3,
    country: 'South Korea',
  },
  {
    id: '47',
    name: 'Hyundai',
    industry: 'Automotive',
    location: 'Seoul, South Korea',
    employees: 120000,
    founded: 1967,
    revenue: '$115B+',
    description: 'South Korean multinational automotive manufacturer',
    logo: '🚙',
    rating: 4.4,
    country: 'South Korea',
  },
  {
    id: '48',
    name: 'Sony',
    industry: 'Technology',
    location: 'Tokyo, Japan',
    employees: 109700,
    founded: 1946,
    revenue: '$88B+',
    description: 'Multinational conglomerate corporation',
    logo: '🎮',
    rating: 4.5,
    country: 'Japan',
  },
  {
    id: '49',
    name: 'Toyota',
    industry: 'Automotive',
    location: 'Toyota City, Japan',
    employees: 375000,
    founded: 1937,
    revenue: '$275B+',
    description: 'Japanese multinational automotive manufacturer',
    logo: '🚗',
    rating: 4.7,
    country: 'Japan',
  },
  {
    id: '50',
    name: 'Honda',
    industry: 'Automotive',
    location: 'Tokyo, Japan',
    employees: 204000,
    founded: 1948,
    revenue: '$129B+',
    description: 'Japanese multinational conglomerate corporation',
    logo: '🏍️',
    rating: 4.5,
    country: 'Japan',
  },
  {
    id: '51',
    name: 'Nintendo',
    industry: 'Gaming',
    location: 'Kyoto, Japan',
    employees: 7717,
    founded: 1889,
    revenue: '$15B+',
    description: 'Japanese multinational video game company',
    logo: '🎮',
    rating: 4.6,
    country: 'Japan',
  },
  {
    id: '52',
    name: 'Alibaba',
    industry: 'E-commerce',
    location: 'Hangzhou, China',
    employees: 235216,
    founded: 1999,
    revenue: '$134B+',
    description: 'Chinese multinational technology company',
    logo: '🛒',
    rating: 4.4,
    country: 'China',
  },
  {
    id: '53',
    name: 'Tencent',
    industry: 'Technology',
    location: 'Shenzhen, China',
    employees: 116213,
    founded: 1998,
    revenue: '$87B+',
    description: 'Chinese multinational technology and entertainment conglomerate',
    logo: '💬',
    rating: 4.5,
    country: 'China',
  },
  {
    id: '54',
    name: 'Huawei',
    industry: 'Technology',
    location: 'Shenzhen, China',
    employees: 207000,
    founded: 1987,
    revenue: '$99B+',
    description: 'Chinese multinational technology corporation',
    logo: '📱',
    rating: 4.3,
    country: 'China',
  },
  {
    id: '55',
    name: 'ByteDance',
    industry: 'Technology',
    location: 'Beijing, China',
    employees: 150000,
    founded: 2012,
    revenue: '$80B+',
    description: 'Chinese internet technology company',
    logo: '🎵',
    rating: 4.4,
    country: 'China',
  },
  // More Indian Companies
  {
    id: '56',
    name: 'Paytm',
    industry: 'Fintech',
    location: 'Noida, India',
    employees: 20000,
    founded: 2010,
    revenue: '$1B+',
    description: 'Indian digital payment and financial services company',
    logo: '💳',
    rating: 4.0,
    country: 'India',
  },
  {
    id: '57',
    name: 'PhonePe',
    industry: 'Fintech',
    location: 'Bangalore, India',
    employees: 3500,
    founded: 2015,
    revenue: '$500M+',
    description: 'Indian digital payments platform',
    logo: '📱',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '58',
    name: 'OYO Rooms',
    industry: 'Hospitality',
    location: 'Gurugram, India',
    employees: 17000,
    founded: 2013,
    revenue: '$1B+',
    description: 'Hospitality company that operates a chain of hotels',
    logo: '🏨',
    rating: 3.9,
    country: 'India',
  },
  {
    id: '59',
    name: 'Ola Cabs',
    industry: 'Transportation',
    location: 'Bangalore, India',
    employees: 5000,
    founded: 2010,
    revenue: '$2B+',
    description: 'Ridesharing company',
    logo: '🚕',
    rating: 4.1,
    country: 'India',
  },
  {
    id: '60',
    name: 'BYJU\'S',
    industry: 'Education',
    location: 'Bangalore, India',
    employees: 15000,
    founded: 2011,
    revenue: '$1B+',
    description: 'Educational technology and online tutoring firm',
    logo: '📚',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '61',
    name: 'Razorpay',
    industry: 'Fintech',
    location: 'Bangalore, India',
    employees: 3500,
    founded: 2014,
    revenue: '$300M+',
    description: 'Payment gateway and financial services company',
    logo: '⚡',
    rating: 4.4,
    country: 'India',
  },
  {
    id: '62',
    name: 'Freshworks',
    industry: 'Technology',
    location: 'Chennai, India',
    employees: 5000,
    founded: 2010,
    revenue: '$500M+',
    description: 'Customer engagement software company',
    logo: '🔧',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '63',
    name: 'Zoho Corporation',
    industry: 'Technology',
    location: 'Chennai, India',
    employees: 12000,
    founded: 1996,
    revenue: '$1B+',
    description: 'Multinational technology company that makes web-based business tools',
    logo: '🌐',
    rating: 4.5,
    country: 'India',
  },
  {
    id: '64',
    name: 'MakeMyTrip',
    industry: 'Travel',
    location: 'Gurugram, India',
    employees: 5000,
    founded: 2000,
    revenue: '$700M+',
    description: 'Online travel company',
    logo: '✈️',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '65',
    name: 'Nykaa',
    industry: 'E-commerce',
    location: 'Mumbai, India',
    employees: 2500,
    founded: 2012,
    revenue: '$500M+',
    description: 'Indian e-commerce company focused on beauty and wellness',
    logo: '💄',
    rating: 4.3,
    country: 'India',
  },
  {
    id: '66',
    name: 'BigBasket',
    industry: 'E-commerce',
    location: 'Bangalore, India',
    employees: 15000,
    founded: 2011,
    revenue: '$1B+',
    description: 'Online grocery delivery service',
    logo: '🥬',
    rating: 4.1,
    country: 'India',
  },
  {
    id: '67',
    name: 'Policybazaar',
    industry: 'Fintech',
    location: 'Gurugram, India',
    employees: 3000,
    founded: 2008,
    revenue: '$200M+',
    description: 'Insurance aggregator and multinational financial technology company',
    logo: '🛡️',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '68',
    name: 'Myntra',
    industry: 'E-commerce',
    location: 'Bangalore, India',
    employees: 4000,
    founded: 2007,
    revenue: '$2B+',
    description: 'E-commerce company primarily focused on fashion and lifestyle products',
    logo: '👗',
    rating: 4.2,
    country: 'India',
  },
  {
    id: '69',
    name: 'Snapdeal',
    industry: 'E-commerce',
    location: 'New Delhi, India',
    employees: 1000,
    founded: 2010,
    revenue: '$500M+',
    description: 'Indian e-commerce company',
    logo: '🛍️',
    rating: 3.9,
    country: 'India',
  },
  {
    id: '70',
    name: 'Cred',
    industry: 'Fintech',
    location: 'Bangalore, India',
    employees: 1500,
    founded: 2018,
    revenue: '$200M+',
    description: 'Indian fintech company',
    logo: '💎',
    rating: 4.4,
    country: 'India',
  },
  // More US Companies
  {
    id: '71',
    name: 'Uber',
    industry: 'Transportation',
    location: 'San Francisco, USA',
    employees: 32800,
    founded: 2009,
    revenue: '$37B+',
    description: 'Mobility as a service provider',
    logo: '🚗',
    rating: 4.2,
    country: 'USA',
  },
  {
    id: '72',
    name: 'Airbnb',
    industry: 'Hospitality',
    location: 'San Francisco, USA',
    employees: 6900,
    founded: 2008,
    revenue: '$10B+',
    description: 'Online marketplace for lodging and tourism activities',
    logo: '🏠',
    rating: 4.5,
    country: 'USA',
  },
  {
    id: '73',
    name: 'Salesforce',
    industry: 'Technology',
    location: 'San Francisco, USA',
    employees: 79390,
    founded: 1999,
    revenue: '$34B+',
    description: 'Cloud-based software company',
    logo: '☁️',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '74',
    name: 'Oracle',
    industry: 'Technology',
    location: 'Austin, USA',
    employees: 164000,
    founded: 1977,
    revenue: '$50B+',
    description: 'Multinational computer technology corporation',
    logo: '🗄️',
    rating: 4.3,
    country: 'USA',
  },
  {
    id: '75',
    name: 'Adobe',
    industry: 'Technology',
    location: 'San Jose, USA',
    employees: 29239,
    founded: 1982,
    revenue: '$19B+',
    description: 'Computer software company',
    logo: '🎨',
    rating: 4.6,
    country: 'USA',
  },
  {
    id: '76',
    name: 'Cisco',
    industry: 'Technology',
    location: 'San Jose, USA',
    employees: 83300,
    founded: 1984,
    revenue: '$57B+',
    description: 'Multinational technology conglomerate',
    logo: '🌐',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '77',
    name: 'SpaceX',
    industry: 'Aerospace',
    location: 'Hawthorne, USA',
    employees: 13000,
    founded: 2002,
    revenue: '$8B+',
    description: 'Aerospace manufacturer and space transportation company',
    logo: '🚀',
    rating: 4.7,
    country: 'USA',
  },
  {
    id: '78',
    name: 'Boeing',
    industry: 'Aerospace',
    location: 'Chicago, USA',
    employees: 171000,
    founded: 1916,
    revenue: '$77B+',
    description: 'Multinational corporation that designs and manufactures airplanes',
    logo: '✈️',
    rating: 4.2,
    country: 'USA',
  },
  {
    id: '79',
    name: 'Pfizer',
    industry: 'Pharmaceutical',
    location: 'New York, USA',
    employees: 83000,
    founded: 1849,
    revenue: '$100B+',
    description: 'American multinational pharmaceutical and biotechnology corporation',
    logo: '💊',
    rating: 4.5,
    country: 'USA',
  },
  {
    id: '80',
    name: 'Johnson & Johnson',
    industry: 'Healthcare',
    location: 'New Brunswick, USA',
    employees: 155000,
    founded: 1886,
    revenue: '$95B+',
    description: 'American multinational corporation developing medical devices and pharmaceuticals',
    logo: '⚕️',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '81',
    name: 'Walmart',
    industry: 'Retail',
    location: 'Bentonville, USA',
    employees: 2300000,
    founded: 1962,
    revenue: '$611B+',
    description: 'American multinational retail corporation',
    logo: '🏬',
    rating: 4.3,
    country: 'USA',
  },
  {
    id: '82',
    name: 'Coca-Cola',
    industry: 'Food & Beverage',
    location: 'Atlanta, USA',
    employees: 82500,
    founded: 1892,
    revenue: '$43B+',
    description: 'American multinational beverage corporation',
    logo: '🥤',
    rating: 4.4,
    country: 'USA',
  },
  {
    id: '83',
    name: 'PepsiCo',
    industry: 'Food & Beverage',
    location: 'Purchase, USA',
    employees: 309000,
    founded: 1965,
    revenue: '$86B+',
    description: 'American multinational food and beverage corporation',
    logo: '🥤',
    rating: 4.3,
    country: 'USA',
  },
  {
    id: '84',
    name: 'Nike',
    industry: 'Apparel',
    location: 'Beaverton, USA',
    employees: 79100,
    founded: 1964,
    revenue: '$51B+',
    description: 'American multinational corporation engaged in footwear and apparel',
    logo: '👟',
    rating: 4.5,
    country: 'USA',
  },
  {
    id: '85',
    name: 'Starbucks',
    industry: 'Food & Beverage',
    location: 'Seattle, USA',
    employees: 402000,
    founded: 1971,
    revenue: '$36B+',
    description: 'American multinational chain of coffeehouses',
    logo: '☕',
    rating: 4.3,
    country: 'USA',
  },
  // More Global Companies
  {
    id: '86',
    name: 'Shell',
    industry: 'Energy',
    location: 'London, UK',
    employees: 82000,
    founded: 1907,
    revenue: '$381B+',
    description: 'British multinational oil and gas company',
    logo: '⛽',
    rating: 4.2,
    country: 'UK',
  },
  {
    id: '87',
    name: 'BP',
    industry: 'Energy',
    location: 'London, UK',
    employees: 64700,
    founded: 1909,
    revenue: '$248B+',
    description: 'British multinational oil and gas company',
    logo: '🛢️',
    rating: 4.1,
    country: 'UK',
  },
  {
    id: '88',
    name: 'Unilever',
    industry: 'Consumer Goods',
    location: 'London, UK',
    employees: 127000,
    founded: 1929,
    revenue: '$60B+',
    description: 'British multinational consumer goods company',
    logo: '🧼',
    rating: 4.4,
    country: 'UK',
  },
  {
    id: '89',
    name: 'HSBC',
    industry: 'Finance',
    location: 'London, UK',
    employees: 219000,
    founded: 1865,
    revenue: '$52B+',
    description: 'British multinational investment bank and financial services',
    logo: '🏦',
    rating: 4.3,
    country: 'UK',
  },
  {
    id: '90',
    name: 'Barclays',
    industry: 'Finance',
    location: 'London, UK',
    employees: 83500,
    founded: 1690,
    revenue: '$28B+',
    description: 'British multinational investment bank',
    logo: '💰',
    rating: 4.2,
    country: 'UK',
  },
  {
    id: '91',
    name: 'Rolls-Royce',
    industry: 'Aerospace',
    location: 'London, UK',
    employees: 42000,
    founded: 1906,
    revenue: '$18B+',
    description: 'British multinational aerospace and defense company',
    logo: '✈️',
    rating: 4.4,
    country: 'UK',
  },
  {
    id: '92',
    name: 'Emirates',
    industry: 'Aviation',
    location: 'Dubai, UAE',
    employees: 105000,
    founded: 1985,
    revenue: '$27B+',
    description: 'One of the two flag carriers of the United Arab Emirates',
    logo: '✈️',
    rating: 4.6,
    country: 'UAE',
  },
  {
    id: '93',
    name: 'Etihad Airways',
    industry: 'Aviation',
    location: 'Abu Dhabi, UAE',
    employees: 21000,
    founded: 2003,
    revenue: '$5B+',
    description: 'Second flag carrier of the United Arab Emirates',
    logo: '🛫',
    rating: 4.4,
    country: 'UAE',
  },
  {
    id: '94',
    name: 'Saudi Aramco',
    industry: 'Energy',
    location: 'Dhahran, Saudi Arabia',
    employees: 70000,
    founded: 1933,
    revenue: '$600B+',
    description: 'Saudi Arabian public petroleum and natural gas company',
    logo: '⛽',
    rating: 4.5,
    country: 'Saudi Arabia',
  },
  {
    id: '95',
    name: 'Singtel',
    industry: 'Telecommunications',
    location: 'Singapore',
    employees: 23000,
    founded: 1879,
    revenue: '$15B+',
    description: 'Singaporean telecommunications conglomerate',
    logo: '📡',
    rating: 4.2,
    country: 'Singapore',
  },
  {
    id: '96',
    name: 'DBS Bank',
    industry: 'Finance',
    location: 'Singapore',
    employees: 32000,
    founded: 1968,
    revenue: '$15B+',
    description: 'Singaporean multinational banking and financial services corporation',
    logo: '🏦',
    rating: 4.5,
    country: 'Singapore',
  },
  {
    id: '97',
    name: 'Grab',
    industry: 'Technology',
    location: 'Singapore',
    employees: 11000,
    founded: 2012,
    revenue: '$2B+',
    description: 'Southeast Asian technology company offering ride-hailing services',
    logo: '🚗',
    rating: 4.3,
    country: 'Singapore',
  },
  {
    id: '98',
    name: 'Shopee',
    industry: 'E-commerce',
    location: 'Singapore',
    employees: 10000,
    founded: 2015,
    revenue: '$6B+',
    description: 'Singaporean multinational technology company specializing in e-commerce',
    logo: '🛒',
    rating: 4.4,
    country: 'Singapore',
  },
  {
    id: '99',
    name: 'Atlassian',
    industry: 'Technology',
    location: 'Sydney, Australia',
    employees: 11000,
    founded: 2002,
    revenue: '$4B+',
    description: 'Australian software company that develops products for software developers',
    logo: '🔧',
    rating: 4.5,
    country: 'Australia',
  },
  {
    id: '100',
    name: 'Canva',
    industry: 'Technology',
    location: 'Sydney, Australia',
    employees: 4000,
    founded: 2012,
    revenue: '$2B+',
    description: 'Australian graphic design platform',
    logo: '🎨',
    rating: 4.6,
    country: 'Australia',
  },
  {
    id: '101',
    name: 'Qantas',
    industry: 'Aviation',
    location: 'Sydney, Australia',
    employees: 28000,
    founded: 1920,
    revenue: '$18B+',
    description: 'Australian flag carrier airline',
    logo: '🦘',
    rating: 4.3,
    country: 'Australia',
  },
  {
    id: '102',
    name: 'BHP',
    industry: 'Mining',
    location: 'Melbourne, Australia',
    employees: 80000,
    founded: 1885,
    revenue: '$65B+',
    description: 'Australian multinational mining and metals company',
    logo: '⛏️',
    rating: 4.4,
    country: 'Australia',
  },
  {
    id: '103',
    name: 'Rio Tinto',
    industry: 'Mining',
    location: 'London, UK',
    employees: 47000,
    founded: 1873,
    revenue: '$63B+',
    description: 'British-Australian multinational mining company',
    logo: '💎',
    rating: 4.3,
    country: 'Australia',
  },
  {
    id: '104',
    name: 'Petrobras',
    industry: 'Energy',
    location: 'Rio de Janeiro, Brazil',
    employees: 45000,
    founded: 1953,
    revenue: '$124B+',
    description: 'Brazilian multinational corporation in the petroleum industry',
    logo: '⛽',
    rating: 4.1,
    country: 'Brazil',
  },
  {
    id: '105',
    name: 'Banco do Brasil',
    industry: 'Finance',
    location: 'Brasilia, Brazil',
    employees: 92000,
    founded: 1808,
    revenue: '$28B+',
    description: 'Brazilian financial services company',
    logo: '🏦',
    rating: 4.2,
    country: 'Brazil',
  },
];

// ... existing helper functions ...

// Simulate API delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// Mock API function to fetch companies with filters and pagination
export async function fetchCompanies(
  filters: FilterOptions,
  page: number = 1,
  itemsPerPage: number = 10
): Promise<{ companies: Company[]; pagination: PaginationInfo }> {
  // Simulate API call delay
  await delay(500);

  // Simulate random errors (3% chance)
  if (Math.random() < 0.03) {
    throw new Error('Failed to fetch companies. Please try again.');
  }

  let filteredCompanies = [...mockCompanies];

  // Apply search filter
  if (filters.search) {
    const searchLower = filters.search.toLowerCase();
    filteredCompanies = filteredCompanies.filter(company =>
      company.name.toLowerCase().includes(searchLower) ||
      company.description.toLowerCase().includes(searchLower) ||
      company.country.toLowerCase().includes(searchLower)
    );
  }

  // Apply industry filter
  if (filters.industry && filters.industry !== 'all') {
    filteredCompanies = filteredCompanies.filter(
      company => company.industry === filters.industry
    );
  }

  // Apply location filter
  if (filters.location && filters.location !== 'all') {
    filteredCompanies = filteredCompanies.filter(
      company => company.location === filters.location
    );
  }

  // Apply sorting
  filteredCompanies.sort((a, b) => {
    let comparison = 0;
    
    switch (filters.sortBy) {
      case 'name':
        comparison = a.name.localeCompare(b.name);
        break;
      case 'location':
        comparison = a.location.localeCompare(b.location);
        break;
      case 'industry':
        comparison = a.industry.localeCompare(b.industry);
        break;
      case 'employees':
        comparison = a.employees - b.employees;
        break;
      case 'founded':
        comparison = a.founded - b.founded;
        break;
    }

    return filters.sortOrder === 'asc' ? comparison : -comparison;
  });

  // Calculate pagination
  const totalItems = filteredCompanies.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const startIndex = (page - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const paginatedCompanies = filteredCompanies.slice(startIndex, endIndex);

  return {
    companies: paginatedCompanies,
    pagination: {
      currentPage: page,
      totalPages,
      totalItems,
      itemsPerPage,
    },
  };
}

// Get unique industries for filter dropdown
export function getIndustries(): string[] {
  const industries = new Set(mockCompanies.map(c => c.industry));
  return Array.from(industries).sort();
}

// Get unique locations for filter dropdown
export function getLocations(): string[] {
  const locations = new Set(mockCompanies.map(c => c.location));
  return Array.from(locations).sort();
}

/* 
  HOW TO REPLACE WITH REAL API:
  
  Replace the fetchCompanies function with actual API calls:
  
  export async function fetchCompanies(
    filters: FilterOptions,
    page: number = 1,
    itemsPerPage: number = 10
  ): Promise<{ companies: Company[]; pagination: PaginationInfo }> {
    const params = new URLSearchParams({
      search: filters.search,
      industry: filters.industry,
      location: filters.location,
      sortBy: filters.sortBy,
      sortOrder: filters.sortOrder,
      page: page.toString(),
      limit: itemsPerPage.toString(),
    });

    const response = await fetch(`http://your-api-url/api/companies?${params}`, {
      headers: {
        'Content-Type': 'application/json',
        // Add authentication headers if needed
        // 'Authorization': `Bearer ${your_token}`,
      },
    });

    if (!response.ok) {
      throw new Error('Failed to fetch companies');
    }

    return await response.json();
  }
*/
